#!/bin/bash
code --install-extension 4ops.terraform
code --install-extension 766b.go-outliner
code --install-extension aaron-bond.better-comments
code --install-extension actboy168.lua-debug
code --install-extension adpyke.vscode-sql-formatter
code --install-extension aeschli.vscode-css-formatter
code --install-extension ahmadawais.shades-of-purple
code --install-extension akamud.vscode-theme-onedark
code --install-extension alefragnani.bookmarks
code --install-extension alefragnani.project-manager
code --install-extension alexcvzz.vscode-sqlite
code --install-extension alexisvt.flutter-snippets
code --install-extension amandeepmittal.pug
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension angular.ng-template
code --install-extension anseki.vscode-color
code --install-extension aquasecurityofficial.trivy-vulnerability-scanner
code --install-extension arah24.moon
code --install-extension asvetliakov.vscode-neovim
code --install-extension austenc.laravel-blade-spacer
code --install-extension batisteo.vscode-django
code --install-extension bibhasdn.django-snippets
code --install-extension bierner.markdown-checkbox
code --install-extension bierner.markdown-emoji
code --install-extension bierner.markdown-footnotes
code --install-extension bierner.markdown-image-size
code --install-extension bierner.markdown-mermaid
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bitwisecook.tcl
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bradlc.vscode-tailwindcss
code --install-extension bung87.rails
code --install-extension bung87.vscode-gemfile
code --install-extension burkeholland.simple-react-snippets
code --install-extension castwide.solargraph
code --install-extension chris-noring.node-snippets
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codestream.codestream
code --install-extension codezombiech.gitignore
code --install-extension codingyu.laravel-goto-view
code --install-extension cschlosser.doxdocgen
code --install-extension csstools.postcss
code --install-extension ctf0.laravel-goto-controller
code --install-extension damianbal.vs-phpclassgen
code --install-extension damms005.devdb
code --install-extension danielpinto8zz6.c-cpp-compile-run
code --install-extension dart-code.dart-code
code --install-extension dart-code.flutter
code --install-extension davidanson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension denoland.vscode-deno
code --install-extension dhoeric.ansible-vault
code --install-extension digitalbrainstem.javascript-ejs-support
code --install-extension donjayamanne.jquerysnippets
code --install-extension donjayamanne.python-environment-manager
code --install-extension donjayamanne.python-extension-pack
code --install-extension dotjoshjohnson.xml
code --install-extension dracula-theme.theme-dracula
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension dustypomerleau.rust-syntax
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension exiasr.hadolint
code --install-extension fallenmax.mithril-emmet
code --install-extension federicovarela.pipenv-scripts
code --install-extension felipecaputo.git-project-manager
code --install-extension figma.figma-vscode-extension
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.docker-explorer
code --install-extension formulahendry.docker-extension-pack
code --install-extension foxundermoon.next-js
code --install-extension franneck94.c-cpp-runner
code --install-extension funkyremi.vscode-google-translate
code --install-extension gencer.html-slim-scss-css-class-completion
code --install-extension george3447.docker-run
code --install-extension georgewfraser.vscode-javac
code --install-extension gimly81.fortran
code --install-extension github.codespaces
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.github-vscode-theme
code --install-extension github.remotehub
code --install-extension github.vscode-codeql
code --install-extension github.vscode-github-actions
code --install-extension github.vscode-pull-request-github
code --install-extension gitpod.gitpod-desktop
code --install-extension gitpod.gitpod-remote-ssh
code --install-extension glenn2223.live-sass
code --install-extension glitchbl.laravel-create-view
code --install-extension golang.go
code --install-extension grapecity.gc-excelviewer
code --install-extension graphql.vscode-graphql
code --install-extension graphql.vscode-graphql-syntax
code --install-extension groksrc.ruby
code --install-extension gruntfuggly.todo-tree
code --install-extension hackmd.vscode-hackmd
code --install-extension hansec.fortran-ls
code --install-extension hashicorp.terraform
code --install-extension hbenl.vscode-test-explorer
code --install-extension hediet.vscode-drawio
code --install-extension henriiik.docker-linter
code --install-extension hollowtree.vue-snippets
code --install-extension hoovercj.ruby-linter
code --install-extension hridoy.rails-snippets
code --install-extension hridoy.wordpress
code --install-extension huizhou.githd
code --install-extension humao.rest-client
code --install-extension hwencc.html-tag-wrapper
code --install-extension ibm.output-colorizer
code --install-extension icrawl.discord-vscode
code --install-extension ihunte.laravel-blade-wrapper
code --install-extension ionutvmi.path-autocomplete
code --install-extension ipedrazas.kubernetes-snippets
code --install-extension irongeek.vscode-env
code --install-extension ironmansoftware.powershell-universal
code --install-extension ironmansoftware.powershellprotools
code --install-extension james-yu.latex-workshop
code --install-extension janisdd.vscode-edit-csv
code --install-extension jasonnutter.search-node-modules
code --install-extension jawandarajbir.react-vscode-extension-pack
code --install-extension jebbs.plantuml
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension johnpapa.angular2
code --install-extension johnpapa.vscode-peacock
code --install-extension johnpapa.winteriscoming
code --install-extension jscearcy.rust-doc-viewer
code --install-extension justusadam.language-haskell
code --install-extension kelvin.vscode-sshfs
code --install-extension kevinrose.vsc-python-indent
code --install-extension keyring.lua
code --install-extension kgrzywocz.wsl-path
code --install-extension kisstkondoros.vscode-codemetrics
code --install-extension kleber-swf.unity-code-snippets
code --install-extension kreativ-software.csharpextensions
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension laurencebahiirwa.deno-std-lib-snippets
code --install-extension leizongmin.node-module-intellisense
code --install-extension lfurzewaddock.vscode-wsl-workspacefolder
code --install-extension lunuan.kubernetes-templates
code --install-extension magicstack.magicpython
code --install-extension manasxx.background-cover
code --install-extension marcelovelasquez.flutter-tree
code --install-extension mark-tucker.aws-cli-configure
code --install-extension mathiasfrohlich.kotlin
code --install-extension mattiasbaake.vscode-snippets-for-ansible
code --install-extension mdickin.markdown-shortcuts
code --install-extension mechatroner.rainbow-csv
code --install-extension mehedidracula.php-constructor
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mhutchie.git-graph
code --install-extension michelemelluso.code-beautifier
code --install-extension miguel-savignano.ruby-symbols
code --install-extension miguelsolorio.fluent-icons
code --install-extension mikestead.dotenv
code --install-extension mikhail-arkhipov.r
code --install-extension mindaro-dev.file-downloader
code --install-extension mintlify.document
code --install-extension miramac.vscode-exec-node
code --install-extension misogi.ruby-rubocop
code --install-extension mitaki28.vscode-clang
code --install-extension mongodb.mongodb-vscode
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension mosapride.zenkaku
code --install-extension mrmlnc.vscode-apache
code --install-extension mrmlnc.vscode-autoprefixer
code --install-extension mrmlnc.vscode-duplicate
code --install-extension mrmlnc.vscode-pugbeautify
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-azureappservice
code --install-extension ms-azuretools.vscode-azurecontainerapps
code --install-extension ms-azuretools.vscode-azurefunctions
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-azurestaticwebapps
code --install-extension ms-azuretools.vscode-azurestorage
code --install-extension ms-azuretools.vscode-azurevirtualmachines
code --install-extension ms-azuretools.vscode-cosmosdb
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-ceintl.vscode-language-pack-ja
code --install-extension ms-kubernetes-tools.kind-vscode
code --install-extension ms-kubernetes-tools.vscode-aks-tools
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-mssql.data-workspace-vscode
code --install-extension ms-mssql.mssql
code --install-extension ms-mssql.sql-bindings-vscode
code --install-extension ms-mssql.sql-database-projects-vscode
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.azure-repos
code --install-extension ms-vscode.azurecli
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.hexeditor
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.mono-debug
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-repositories
code --install-extension ms-vscode.remote-server
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vscode.vscode-node-azure-pack
code --install-extension ms-vscode.vscode-serial-monitor
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.vscode-react-native
code --install-extension msyrus.go-doc
code --install-extension mtxr.sqltools
code --install-extension mushan.vscode-paste-image
code --install-extension naoray.laravel-goto-components
code --install-extension naumovs.color-highlight
code --install-extension neilbrayfield.php-docblocker
code --install-extension nikolapaunovic.tkinter-snippets
code --install-extension njpwerner.autodocstring
code --install-extension nodesource.vscode-for-node-js-development-pack
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension okteto.remote-kubernetes
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel-extension-pack
code --install-extension onecentlin.laravel5-snippets
code --install-extension orta.vscode-jest
code --install-extension p1c2u.docker-compose
code --install-extension pflannery.vscode-versionlens
code --install-extension pgl.laravel-jump-controller
code --install-extension pizzacat83.codic
code --install-extension pkief.material-icon-theme
code --install-extension pkief.material-product-icons
code --install-extension pkosta2005.heroku-command
code --install-extension platformio.platformio-ide
code --install-extension pomdtr.excalidraw-editor
code --install-extension pranaygp.vscode-css-peek
code --install-extension premparihar.gotestexplorer
code --install-extension pulkitgangwar.nextjs-snippets
code --install-extension rafaelmaiolla.remote-vscode
code --install-extension rangav.vscode-thunder-client
code --install-extension rashwell.tcl
code --install-extension rdebugger.r-debugger
code --install-extension redhat.ansible
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-rsp-ui
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension reditorsupport.r
code --install-extension rifi2k.format-html-in-php
code --install-extension ritwickdey.liveserver
code --install-extension robert-brunhage.flutter-riverpod-snippets
code --install-extension rogalmic.bash-debug
code --install-extension run-at-scale.terraform-doc-snippets
code --install-extension rust-lang.rust-analyzer
code --install-extension ryannaddy.laravel-artisan
code --install-extension ryu1kn.partial-diff
code --install-extension samuelcolvin.jinjahtml
code --install-extension samverschueren.final-newline
code --install-extension sdras.night-owl
code --install-extension sdras.vue-vscode-snippets
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension shopify.ruby-lsp
code --install-extension shufo.vscode-blade-formatter
code --install-extension sianglim.slim
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension sidthesloth.html5-boilerplate
code --install-extension snyk-security.snyk-vulnerability-scanner
code --install-extension soerenuhrbach.vscode-deepl
code --install-extension sonarsource.sonarlint-vscode
code --install-extension sozercan.slack
code --install-extension statelyai.stately-vscode
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension sumneko.lua
code --install-extension swellaby.rust-pack
code --install-extension syler.sass-indented
code --install-extension tamasfe.even-better-toml
code --install-extension techer.open-in-browser
code --install-extension tfsec.tfsec
code --install-extension thekalinga.bootstrap4-vscode
code --install-extension thiscodeworks.savecode
code --install-extension timonwong.shellcheck
code --install-extension toba.vsfire
code --install-extension tobiah.unity-tools
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension tomoki1207.pdf
code --install-extension tomsaunders.vscode-workspace-explorer
code --install-extension twxs.cmake
code --install-extension vadimcn.vscode-lldb
code --install-extension vayan.haml
code --install-extension vincaslt.highlight-matching-tag
code --install-extension vintharas.learn-vim
code --install-extension vmware.vscode-boot-dev-pack
code --install-extension vmware.vscode-spring-boot
code --install-extension vortizhe.simple-ruby-erb
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-boot-dashboard
code --install-extension vscjava.vscode-spring-initializr
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension vsls-contrib.gitdoc
code --install-extension vue.volar
code --install-extension waderyan.gitblame
code --install-extension walkme.ruby-extension-pack
code --install-extension wallabyjs.quokka-vscode
code --install-extension wayou.vscode-todo-highlight
code --install-extension webfreak.debug
code --install-extension whatwedo.twig
code --install-extension wholroyd.jinja
code --install-extension wix.vscode-import-cost
code --install-extension wordpresstoolbox.wordpress-toolbox
code --install-extension wscats.eno
code --install-extension wscats.qf
code --install-extension xabikos.javascriptsnippets
code --install-extension xabikos.reactsnippets
code --install-extension xadillax.viml
code --install-extension xdebug.php-debug
code --install-extension xdebug.php-pack
code --install-extension xyz.local-history
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
code --install-extension zaczero.bootstrap-v4-snippets
code --install-extension zainchen.json
code --install-extension zhuangtongfa.material-theme
code --install-extension zignd.html-css-class-completion
code --install-extension zobo.php-intellisense
code --install-extension zxh404.vscode-proto3
code --install-extension bbenoist.nix
